// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instruction {
    #[prost(oneof="instruction::Item", tags="1, 2, 3, 4")]
    pub item: ::core::option::Option<instruction::Item>,
}
/// Nested message and enum types in `Instruction`.
pub mod instruction {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Item {
        #[prost(message, tag="1")]
        Mint(super::Mint),
        #[prost(message, tag="2")]
        Burn(super::Burn),
        #[prost(message, tag="3")]
        Transfer(super::Transfer),
        #[prost(message, tag="4")]
        InitializedAccount(super::InitializedAccount),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(string, tag="1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub instructions: ::prost::alloc::vec::Vec<Instruction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transactions {
    #[prost(message, repeated, tag="3")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(string, tag="2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub to: ::prost::alloc::string::String,
    #[prost(double, tag="4")]
    pub amount: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mint {
    #[prost(string, tag="2")]
    pub to: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub amount: f64,
    #[prost(enumeration="mint::Type", tag="4")]
    pub r#type: i32,
}
/// Nested message and enum types in `Mint`.
pub mod mint {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Unset = 0,
        Mint = 1,
        RegularDriver = 2,
        NoSplit = 3,
        AiTrainer = 4,
        Operational = 5,
        Reward = 6,
        FleetManager = 7,
        FleetDriver = 8,
        MapConsumption = 9,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Unset => "UNSET",
                Type::Mint => "MINT",
                Type::RegularDriver => "REGULAR_DRIVER",
                Type::NoSplit => "NO_SPLIT",
                Type::AiTrainer => "AI_TRAINER",
                Type::Operational => "OPERATIONAL",
                Type::Reward => "REWARD",
                Type::FleetManager => "FLEET_MANAGER",
                Type::FleetDriver => "FLEET_DRIVER",
                Type::MapConsumption => "MAP_CONSUMPTION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSET" => Some(Self::Unset),
                "MINT" => Some(Self::Mint),
                "REGULAR_DRIVER" => Some(Self::RegularDriver),
                "NO_SPLIT" => Some(Self::NoSplit),
                "AI_TRAINER" => Some(Self::AiTrainer),
                "OPERATIONAL" => Some(Self::Operational),
                "REWARD" => Some(Self::Reward),
                "FLEET_MANAGER" => Some(Self::FleetManager),
                "FLEET_DRIVER" => Some(Self::FleetDriver),
                "MAP_CONSUMPTION" => Some(Self::MapConsumption),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Burn {
    #[prost(string, tag="2")]
    pub from: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub amount: f64,
    #[prost(enumeration="burn::Type", tag="4")]
    pub r#type: i32,
}
/// Nested message and enum types in `Burn`.
pub mod burn {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Type {
        Unset = 0,
        Burn = 1,
        MapCreate = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Type::Unset => "UNSET",
                Type::Burn => "BURN",
                Type::MapCreate => "MAP_CREATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSET" => Some(Self::Unset),
                "BURN" => Some(Self::Burn),
                "MAP_CREATE" => Some(Self::MapCreate),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializedAccount {
    #[prost(string, tag="1")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub mint: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub owner: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
