pub const SOLANA_PROGRAM_ACCOUNT: &str = "11111111111111111111111111111111";
pub const TOKEN_PROGRAM: &str = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
pub const HONEY_CONTRACT_ADDRESS: &str = "4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy";

pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_LIB: &str = "EEjwuvCMVYjgHUeX1BM9qmUog59Pft88c3jbt2ATwcJw";
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_LIBCREATE_ACCOUNT: u8 = 232; // 0xe8

// Program
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM: &str = "BNH1dUp3ExFbgo3YctSqQbJXRFn3ffkwbcmSas8azfaW";

// Instructions
pub const HONEY_TOKEN_SPLITTING_INSTRUCTION_BYTE: u8 = 172; // 0xac
pub const HONEY_NO_TOKEN_SPLITTING_INSTRUCTION_BYTE: u8 = 179; // 0xb3
pub const HONEY_REGULAR_DRIVER_INSTRUCTION_BYTE: u8 = 151; // 0x97
pub const HONEY_AI_TRAINER_INSTRUCTION_BYTE: u8 = 241; // 0xf1

pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_CREATE_ACCOUNT: u8 = 46; // 0x2e
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_CREATE_ACCOUNT_2: u8 = 125; // 0x7d
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_CREATE_ACCOUNT_3: u8 = 248; // 0xf8
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_CREATE_ACCOUNT_4: u8 = 182; // b6

pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_IGNORE_LIST: [u8; 1] = [
    215, // 0xd7
];

pub const HONEY_TOKEN_DECIMALS: u8 = 9;
